language: java
dist: trusty
sudo: required
group: deprecated-2017Q4

jdk: openjdk8

services:
  - docker

cache:
  directories:
  - .autoconf
  - $HOME/.m2
  - _build
  - deps

before_install:
- git lfs pull

install:
- mvn -N io.takari:maven:wrapper
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

branches:
  only:
    - develop
    - main
    - /.*/
    
stages:
  - compile

jobs:
  include:

    - stage: compile
      os:
        - linux
      script:
        - mvn compile